### ISSUE TITLE
`WsEvent::Closed` not being emitted after calling `WsSender::close()`

### ISSUE THREAD

**Issue by Swarkin** [rerun-io/ewebsock#42]

**Comment by Swarkin** [comment]
Hi there, I havent used this crate in a while and cannot seem to get connecting to anything working at all anymore, sorry.
Getting ewebsock panicks and "unsupported url scheme" errors all over the place.

**Comment by Swarkin** [comment]
Here is the panic message for when I try to connect to any `wss://` URL

<details>

<summary>Source code</summary>

```rs
use std::thread::sleep;
use std::time::Duration;

fn main() {
	let (mut tx, rx) = ewebsock::connect("wss://echo.websocket.org", ewebsock::Options::default())
		.unwrap();

	loop {
		if let Some(event) = rx.try_recv() {
			dbg!(event);
		} else {
			sleep(Duration::from_secs(1));
		}
	}
}
```

</details>

<details>

<summary>Panic</summary>

```rs
thread 'ewebsock' panicked at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\rustls-0.23.28\src\crypto\mod.rs:249:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:697
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\panicking.rs:75
   2: core::panicking::panic_display
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\panicking.rs:269
   3: core::option::expect_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\option.rs:2049
   4: enum2$<core::option::Option<rustls::crypto::CryptoProvider> >::expect<rustls::crypto::CryptoProvider>
             at C:\Users\Me\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:958
   5: rustls::crypto::CryptoProvider::get_default_or_install_from_crate_features
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\rustls-0.23.28\src\crypto\mod.rs:248
   6: rustls::client::client_conn::ClientConfig::builder_with_protocol_versions
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\rustls-0.23.28\src\client\client_conn.rs:317       
   7: rustls::client::client_conn::ClientConfig::builder
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\rustls-0.23.28\src\client\client_conn.rs:294       
   8: tungstenite::tls::encryption::rustls::wrap_stream<std::net::tcp::TcpStream>
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tungstenite-0.24.0\src\tls.rs:120
   9: tungstenite::tls::client_tls_with_config<http::request::Request<tuple$<> >,std::net::tcp::TcpStream>
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tungstenite-0.24.0\src\tls.rs:218
  10: tungstenite::client::connect_with_config::try_client_handshake
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tungstenite-0.24.0\src\client.rs:74
  11: tungstenite::client::connect_with_config<tungstenite::client::ClientRequestBuilder>
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tungstenite-0.24.0\src\client.rs:95
  12: ewebsock::native_tungstenite::ws_connect_blocking
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\ewebsock-0.8.0\src\native_tungstenite.rs:165       
  13: ewebsock::native_tungstenite::ws_connect_impl::closure$0
             at C:\Users\Me\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\ewebsock-0.8.0\src\native_tungstenite.rs:135       
  14: core::hint::black_box
             at C:\Users\Me\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\hint.rs:482      
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\ewebsock-mrp.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

</details>

---

This is what happens when i try to connect to anything else

<details>

<summary>Source code</summary>

```rs
use std::thread::sleep;
use std::time::Duration;

fn main() {
	let (mut tx, rx) = ewebsock::connect("ws://echo.websocket.org", ewebsock::Options::default())
		.unwrap();

	loop {
		if let Some(event) = rx.try_recv() {
			dbg!(event);
		} else {
			sleep(Duration::from_secs(1));
		}
	}
}
```

</details>

<details>

<summary>Output</summary>

```
[src\main.rs:10:4] event = Error(
    "Connect: URL error: URL scheme not supported",
)
```

</details>
